### PR TITLE
resolveIdentifier() for _factories keys

### PR DESCRIPTION
**Pull request by oberhamsi**
I'm not sure what the rational behind the current approach is.

My code compiles server-side but on the client I get this exception for relative modules:

```
Can't find module "../apps/example/main"
```

The attached simple patch fixes that by always doing resolveIdentifier(module id) before usign a module id in a key to _factories.

### CODE REVIEW

**Comment by oberhamsi** [comment]
are you interested in this?

**Comment by tobie** [comment]
Sorry, I didn't have the time to look into this earlier as it was unclear to me why it was needed. turns out it's not. the spec mandates calls to define to only use absolute identifiers.

**Comment by oberhamsi** [comment]
thanks for looking into this.

**Comment by tobie** [comment]
Thanks for your understanding.

**Comment by oberhamsi** [comment]
I figured out that what I really wanted is being able to specify multiple `--root` directories. That will fix those strange, relative module ids in `define()` that made trouble.

But I actually use ringo-modulr, not your implementation, so no idea if this is an issue for you.

**Comment by tobie** [comment]
You mean a require.paths array, correct?

I've fixed that in my upcoming node.js port.

**Comment by oberhamsi** [comment]
right, that's what I mean!

**Pull request closed without merging**
